# Generated by Django 4.2.2 on 2023-08-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot', '0004_set_unique_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_name',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
