# Generated by Django 2.2.24 on 2021-08-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot', '0004_set_unique_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_name',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
