# Generated by Django 2.2.24 on 2021-09-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot', '0005_carrot_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='last_run_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
