# Generated by Django 2.2.24 on 2025-01-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot', '0007_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
