# Generated by Django 2.2.28 on 2025-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot', '0008_auto_20250131_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='worker',
            field=models.CharField(default=None, help_text='Worker that executes the task', max_length=100, null=True, verbose_name='Worker'),
        ),
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'ordering': ('-task', '-pk')},
        ),
    ]
