# Generated by Django 5.1.5 on 2025-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot', '0009_messagelog_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
