# Generated by Django 5.1.5 on 2025-05-12 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot', '0010_alter_messagelog_id_alter_scheduledtask_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='priority',
            field=models.IntegerField(blank=True, help_text='1 to 5 suggested, up to 255', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
